config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/rate' => 'rater#create', :as => 'rate'
  root 'static_pages#home'
  get 'static_pages/home'
  resources :ideas 
  resources :products do
    resources :features
  end
  resources :competitors
  resources :features, :only => [:show]
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/competitor.rb
class Competitor < ActiveRecord::Base

  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end 

end 

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  mount_uploader :image, ImageUploader

  STATUS_OPTIONS = [
    'Complete', 
    'In-Development', 
    'In-Design', 
    'On-Deck', 
    'Backlog', 
    'Unscheduled'
  ]

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_one :product
  has_many :product_ideas
  has_many :products, :through => :product_ideas
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  ratyrate_rateable 'business_impact', 'technically_feasible', 'speed_to_market'
end

app/models/kpi.rb
class Kpi < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
require 'googlecharts'
 
class Product < ActiveRecord::Base
  has_one :kpi
  has_many :features
  has_many :product_ideas
  has_many :ideas, :through => :product_ideas
  belongs_to :user
  mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :kpi

def kpi_url
  Gchart.line(:size => '400x400', :legend => ['Dollars per Month'], :axis_with_labels => ['r'], :title => kpi_name,:data => kpi_data) if !kpi_data.nil?
end

private

def kpi_data
  self.kpi.key_data.split(",").map(&:to_i) if !self.kpi.nil? && self.kpi.key_data != ''
end

def kpi_name
  'Revenue'
end

end

app/models/product_idea.rb
class ProductIdea < ActiveRecord::Base
  belongs_to :product
  belongs_to :idea
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :products
  has_many :ideas
  has_many :features 
  has_many :kpis
  has_many :competitors

  ratyrate_rater

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/competitors_controller.rb
class CompetitorsController < ApplicationController 

  before_action :authenticate_user! 

  def index 
    @competitors = Competitor.all
  end 

  def show 
    @competitor = Competitor.find(params[:id]) 
  end 

  def new
    @competitor = Competitor.new
  end

  def create
    @competitor = Competitor.new(competitor_params) 
    @competitor.user_id = current_user.id
    if @competitor.save 
      redirect_to @competitor, notice: "Thanks for adding this competitor"
    else 
      render :new
    end 
  end

  def edit
    @competitor = Competitor.find(params[:id]) 
  end

  def update
    @competitor = Competitor.find(params[:id]) 
    if @competitor.update_attributes(competitor_params) 
      redirect_to @competitor, notice: "Competitor updated"
    else 
      render :edit 
    end
  end

  def destroy
    @competitor = Competitor.find(params[:id]) 
    @competitor.destroy 
    redirect_to competitors_path, alert: "Competitor successfully deleted." 
  end

  private 

  def competitor_params 
    params.require(:competitor).permit(:name, :description, :image, :user_id, :address, :city, :state, :zip, :country, :key_products, :strengths, :weaknesses, :opportunities, :threats, :url)
  end  


end 

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
   def create
     @product = Product.find(params[:product_id])
     @feature = @product.features.create(feature_params)
     redirect_to product_path(@product)
   end

  # def index
  #   @features = Feature.all 
  # end

  def show
    @feature = Feature.find(params[:id]) 
  end

  # def new
  #   @feature = Feature.new
  # end

  # def create
  #   @feature = Feature.new(feature_params) 
  #   if @feature.save 
  #     redirect_to @feature, notice: "Thanks for sharing your feature."
  #   else 
  #     render :new
  #   end 
  # end

  # def edit
  #   @feature = Feature.find(params[:id]) 
  # end

  # def update
  #   @feature = Feature.find(params[:id]) 
  #   if @feature.update_attributes(feature_params) 
  #     redirect_to @feature, notice: "Feature updated"
  #   else 
  #     render :edit 
  #   end
  # end

  # def destroy
  #   @feature = Feature.find(params[:id]) 
  #   @feature.destroy 
  #   redirect_to features_path, alert: "Feature successfully deleted." 
  # end

  # private 

  def feature_params 
     params.require(:feature).permit(:name, :description, :status, :image, :user_id)
  end 
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @ideas = Idea.all 
  end

  def show
    @idea = Idea.find(params[:id]) 
    @idea.user_id = current_user.id
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params) 
    @idea.user_id = current_user.id
    if @idea.save 
      redirect_to @idea, notice: "Thanks for sharing your idea."
    else 
      render :new
    end 
  end

  def edit
    @idea = Idea.find(params[:id]) 
  end

  def update
    @idea = Idea.find(params[:id]) 
    if @idea.update_attributes(idea_params) 
      redirect_to @idea, notice: "Idea updated"
    else 
      render :edit 
    end
  end

  def destroy
    @idea = Idea.find(params[:id]) 
    @idea.destroy 
    redirect_to ideas_path, alert: "Idea successfully deleted." 
  end

  private 

  def idea_params 
    params.require(:idea).permit(:name, :description, :image, :user_id)
  end 
  
end

app/controllers/kpis_controller.rb
class KpisController < ApplicationController 
  
  def import
  end

end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!

  def index
    @products = Product.all 
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product.build_kpi
  end

  def create
    @product = Product.new(product_params) 
    @product.build_kpi(product_params[:kpi_attributes])
    @product.user_id = current_user.id
    if @product.save 
      redirect_to @product, notice: "Your product has been successfully created."
    else 
      render :new
    end 
  end

  def edit
    @product = Product.find(params[:id]) 
  end

  def update
    @product = Product.find(params[:id]) 
    @product.kpi.update_attributes(product_params[:kpi_attributes])
    if @product.update_attributes(product_params) 
      redirect_to @product, notice: "Product updated"
    else 
      render :edit 
    end
  end

  def destroy
    @product = Product.find(params[:id]) 
    @product.destroy 
    redirect_to products_path, alert: "Product successfully deleted." 
  end

  private

  def product_params
      params.require(:product).permit(:name, :description, :image, :user_id, kpi_attributes: [:key_data])
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/_form.html.erb
 <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@idea, :html => {multipart: true}) do |f| %> 
    <%= render "shared/errors", object: @idea %> 

      <div class="form-group">
        <%= f.label :name %> 
        <%= f.text_field :name, class: "form-control"  %> 
      </div> 

      <div class="form-group">
        <%= f.label :description %> 
        <%= f.text_area :description, class: "form-control"  %>
      </div>  

      <div class="form-group">
        <%= f.label :image %> 
        <%= f.file_field :image, class: "form-control"  %> 
      </div> 

      <div class="form-group">
        <%= f.submit "Save Idea", class: "btn btn-primary" %>
      </div> 
     <% end %> 
  </div>
</div>

app/views/ideas/edit.html.erb
<h1>Edit <%= @idea.name %> </h1>
<%= render 'form' %> 

app/views/ideas/index.html.erb
<h1> Ideas </h1>  
<div class="center"> 
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p>Add a <%= link_to "New Idea", new_idea_path %></p>
    <% @ideas.each do |idea| %> 
      <div class="col-md-3"> 

            <h3> 
              <%= link_to(idea.name, idea) %> 
            </h3>
            <p> 
              <%= truncate(idea.description, length: 100, separator: ' ') %> 
            </p> 
      </div> 
    <% end %> 
  </div>
</div>
</div> 

app/views/ideas/new.html.erb
<h1>Add a New Idea</h1>
<%= render 'form' %> 

app/views/ideas/show.html.erb
<h1><%= @idea.name %> </h1>
<div class="row">
  <div class="col-md-4 col-md-offset-2"> 
      <p><%= @idea.description %></p>
      <div>
        <% if current_user %> 
          Potential Business Impact: <%= rating_for @idea, 'business_impact', disable_after_rate: false, star_path: '/images' %> <br> 
          Technically Feasible: <%= rating_for @idea, "technically_feasible", disable_after_rate: false, star_path: '/images' %> <br> 
          Speed to Market: <%= rating_for @idea, "speed_to_market", disable_after_rate: false, star_path: '/images' %> 
        <% end %> 
      </div> 
      <br> 
      <hr>
        <footer> 
          <%= link_to 'Edit', edit_idea_path(@idea)%>  | 
          <%= link_to 'Delete', @idea, method: :delete, data: { confirm: "Are you sure?" } %>  | 
          <%= link_to 'Back', ideas_path %> 
        </footer>
    </div>

  </div> 

</div>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@product, :html => {multipart: true}) do |f| %> 
    <%= render "shared/errors", object: @product %> 
      <div class="form-group">
        <%= f.label :name %> 
        <%= f.text_field :name, class: "form-control" %>
      </div>  

      <div class="form-group">
        <%= f.label :description %> 
        <%= f.text_area :description, class: "form-control" %>
      </div>  
      <%= f.fields_for :kpi do |kf| %>
        <div class="form-group">
          <%= kf.label "Revenue by Month" %>
          <%= kf.text_field :key_data %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :image %> 
        <%= f.file_field :image, class: "form-control" %> 
      </div> 

      <div class="form-group">
        <%= f.submit "Save Product", class: "btn btn-primary" %>
      </div> 
     <% end %> 
  </div>
</div>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %> </h1>
<%= render 'form' %> 

app/views/products/index.html.erb
<h1> Products </h1>  
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p>Add a <%= link_to "New Product", new_product_path %></p>
    <% @products.each do |product| %> 
      <div class="col-md-3"> 

              <h3> 
                <%= link_to(product.name, product) %> 
              </h3>
              <p> 
                <%= truncate(product.description, length: 100, separator: ' ') %> 
              </p> 

      </div> 
    <% end %> 
  </div>
</div>

app/views/products/new.html.erb
<h1>Add a New Product</h1>
<%= render 'form' %> 

app/views/products/show.html.erb
<h1><%= @product.name %> </h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2"> 
      <p><%= @product.description %></p>
      <h2>Product Image</h2>
      <p><%= image_tag @product.image.url %></p>
      <h2>Product Revenue (KPI)</h2>
      <p><%= image_tag @product.kpi_url if !@product.kpi_url.nil? %></p> 
      <h2><%= @product.features.count %> Features</h2>
      <% @product.features.each do |f| %>
        <p><%= link_to f.name, feature_path(f.id) %></p>
      <% end %>

      <h2>Add a feature:</h2>
      <%= render "features/form" %>

      <footer> 
        <%= link_to 'Edit', edit_product_path(@product)%> 
        <%= link_to 'Delete', @product, method: :delete, data: { confirm: "Are you sure?" } %> 
        <%= link_to 'Back', products_path %> 
      </footer> 
  </div>
</div>