config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/rate' => 'rater#create', :as => 'rate'
  root 'static_pages#home'
  get 'static_pages/home'
  resources :ideas 
  resources :products do
    resources :features
  end
  resources :competitors
  resources :features, :only => [:show]
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/competitor.rb
class Competitor < ActiveRecord::Base

  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end 

end 

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  mount_uploader :image, ImageUploader

  STATUS_OPTIONS = [
    'Complete', 
    'In-Development', 
    'In-Design', 
    'On-Deck', 
    'Backlog', 
    'Unscheduled'
  ]

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_one :product
  has_many :product_ideas
  has_many :products, :through => :product_ideas
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  ratyrate_rateable 'business_impact', 'technically_feasible', 'speed_to_market'
end

app/models/kpi.rb
class Kpi < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
require 'googlecharts'
 
class Product < ActiveRecord::Base
  has_one :kpi
  has_many :features
  has_many :product_ideas
  has_many :ideas, :through => :product_ideas
  belongs_to :user
  mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :kpi

def kpi_url
  Gchart.line(:size => '400x400', :legend => ['Dollars per Month'], :axis_with_labels => ['r'], :title => kpi_name,:data => kpi_data) if !kpi_data.nil?
end

private

def kpi_data
  self.kpi.key_data.split(",").map(&:to_i) if !self.kpi.nil? && self.kpi.key_data != ''
end

def kpi_name
  'Revenue'
end

end

app/models/product_idea.rb
class ProductIdea < ActiveRecord::Base
  belongs_to :product
  belongs_to :idea
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :products
  has_many :ideas
  has_many :features 
  has_many :kpis
  has_many :competitors

  ratyrate_rater

end

app/controllers/competitors_controller.rb
class CompetitorsController < ApplicationController 

  before_action :authenticate_user! 

  def index 
    @competitors = Competitor.all
  end 

  def show 
    @competitor = Competitor.find(params[:id]) 
  end 

  def new
    @competitor = Competitor.new
  end

  def create
    @competitor = Competitor.new(competitor_params) 
    @competitor.user_id = current_user.id
    if @competitor.save 
      redirect_to @competitor, notice: "Thanks for adding this competitor"
    else 
      render :new
    end 
  end

  def edit
    @competitor = Competitor.find(params[:id]) 
  end

  def update
    @competitor = Competitor.find(params[:id]) 
    if @competitor.update_attributes(competitor_params) 
      redirect_to @competitor, notice: "Competitor updated"
    else 
      render :edit 
    end
  end

  def destroy
    @competitor = Competitor.find(params[:id]) 
    @competitor.destroy 
    redirect_to competitors_path, alert: "Competitor successfully deleted." 
  end

  private 

  def competitor_params 
    params.require(:competitor).permit(:name, :description, :image, :user_id, :address, :city, :state, :zip, :country, :key_products, :strengths, :weaknesses, :opportunities, :threats, :url)
  end  


end 

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
   def create
     @product = Product.find(params[:product_id])
     @feature = @product.features.create(feature_params)
     redirect_to product_path(@product)
   end

  # def index
  #   @features = Feature.all 
  # end

  def show
    @feature = Feature.find(params[:id]) 
  end

  # def new
  #   @feature = Feature.new
  # end

  # def create
  #   @feature = Feature.new(feature_params) 
  #   if @feature.save 
  #     redirect_to @feature, notice: "Thanks for sharing your feature."
  #   else 
  #     render :new
  #   end 
  # end

  # def edit
  #   @feature = Feature.find(params[:id]) 
  # end

  # def update
  #   @feature = Feature.find(params[:id]) 
  #   if @feature.update_attributes(feature_params) 
  #     redirect_to @feature, notice: "Feature updated"
  #   else 
  #     render :edit 
  #   end
  # end

  # def destroy
  #   @feature = Feature.find(params[:id]) 
  #   @feature.destroy 
  #   redirect_to features_path, alert: "Feature successfully deleted." 
  # end

  # private 

  def feature_params 
     params.require(:feature).permit(:name, :description, :status, :image, :user_id)
  end 
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @ideas = Idea.all 
  end

  def show
    @idea = Idea.find(params[:id]) 
    @idea.user_id = current_user.id
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params) 
    @idea.user_id = current_user.id
    if @idea.save 
      redirect_to @idea, notice: "Thanks for sharing your idea."
    else 
      render :new
    end 
  end

  def edit
    @idea = Idea.find(params[:id]) 
  end

  def update
    @idea = Idea.find(params[:id]) 
    if @idea.update_attributes(idea_params) 
      redirect_to @idea, notice: "Idea updated"
    else 
      render :edit 
    end
  end

  def destroy
    @idea = Idea.find(params[:id]) 
    @idea.destroy 
    redirect_to ideas_path, alert: "Idea successfully deleted." 
  end

  private 

  def idea_params 
    params.require(:idea).permit(:name, :description, :image, :user_id)
  end 
  
end

app/controllers/kpis_controller.rb
class KpisController < ApplicationController 
  
  def import
  end

end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!

  def index
    @products = Product.all 
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @product.build_kpi
  end

  def create
    @product = Product.new(product_params) 
    @product.build_kpi(product_params[:kpi_attributes])
    @product.user_id = current_user.id
    if @product.save 
      redirect_to @product, notice: "Your product has been successfully created."
    else 
      render :new
    end 
  end

  def edit
    @product = Product.find(params[:id]) 
  end

  def update
    @product = Product.find(params[:id]) 
    @product.kpi.update_attributes(product_params[:kpi_attributes])
    if @product.update_attributes(product_params) 
      redirect_to @product, notice: "Product updated"
    else 
      render :edit 
    end
  end

  def destroy
    @product = Product.find(params[:id]) 
    @product.destroy 
    redirect_to products_path, alert: "Product successfully deleted." 
  end

  private

  def product_params
      params.require(:product).permit(:name, :description, :image, :user_id, kpi_attributes: [:key_data])
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/competitors/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@competitor, :html => {multipart: true}) do |f| %> 
    <%= render "shared/errors", object: @competitor %> 

        <h2>Basic Information</h2>

       <div class="form-group">
        <%= f.label :name %> 
        <%= f.text_field :name, class: "form-control" %> 
       </div> 

       <div class="form-group">
        <%= f.label :url, "URL" %> 
        <%= f.text_field :url, class: "form-control" %>

       <div class="form-group">
        <%= f.label :description %> 
        <%= f.text_area :description, class: "form-control"  %> 
       </div> 

       <div class="form-group">
        <%= f.label :address %> 
        <%= f.text_field :address, class: "form-control" %>
       </div> 

       <div class="form-group">
        <%= f.label :city %> 
        <%= f.text_field :city, class: "form-control" %> 
       </div> 

       <div class="form-group">
        <%= f.label :state %> 
        <%= f.text_field :state, class: "form-control" %> 

       <div class="form-group">
        <%= f.label :zip %> 
        <%= f.text_field :zip, class: "form-control" %> 
       </div> 

       <div class="form-group">
        <%= f.label :country %> 
        <%= f.text_field :country, class: "form-control"  %>
       </div> 

       <div class="form-group">
        <%= f.label :image %> 
        <%= f.file_field :image, class: "form-control"  %> 
       </div> 

        <h2> Company Details </h2> 

       <div class="form-group">
        <%= f.label :ceo, "CEO" %> 
        <%= f.text_field :CEO, class: "form-control"  %> 
       </div> 

       <div class="form-group">
        <%= f.label :market_cap %> 
        <%= f.text_field :market_cap, class: "form-control"  %> 
       </div> 

       <div class="form-group">
        <%= f.label :stock_symbol %> 
        <%= f.text_field :stock_symbol, class: "form-control"  %> 
       </div> 

       <div class="form-group">
        <%= f.label :employees %> 
        <%= f.text_field :employees, class: "form-control"  %> 
       </div> 

       <div class="form-group">
        <%= f.label :key_products %> 
        <%= f.text_area :key_products, class: "form-control"  %> 
       </div> 

        <h2> SWOT Analysis </h2>

       <div class="form-group">
        <%= f.label :strengths %> 
        <%= f.text_area :strengths, class: "form-control"   %> 
       </div> 

       <div class="form-group">
        <%= f.label :weaknesses %> 
        <%= f.text_area :weaknesses, class: "form-control"   %>
       </div> 

       <div class="form-group">
        <%= f.label :opportunities %> 
        <%= f.text_area :opportunities, class: "form-control"   %>
       </div> 

       <div class="form-group">
        <%= f.label :threats %> 
        <%= f.text_area :threats, class: "form-control"   %>
       </div> 

       <div class="form-group">
        <%= f.submit "Save Competitor", class: "btn btn-primary" %>
       </div> 
     <% end %> 
  </div>
</div>

app/views/competitors/edit.html.erb
<h1>Edit <%= @competitor.name %></h1>
<%= render 'form' %>

app/views/competitors/index.html.erb
<h1> Competitors </h1>  
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p>Add a <%= link_to "New Competitor", new_competitor_path %></p>

    <% @competitors.each do |competitor| %> 
      <div class="col-md-3"> 

            <h3> 
              <%= link_to(competitor.name, competitor) %> 
            </h3>
            <p> 
              <%= truncate(competitor.description, length: 100, separator: ' ') %> 
            </p> 

      </div> 
    <% end %> 

  </div>
</div>

app/views/competitors/new.html.erb
<h1>Add a New Competitor</h1>
<%= render 'form' %>

app/views/competitors/show.html.erb
<h1><%= @competitor.name %> </h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2"> 
      <p><%= @competitor.description %></p>
      <%= image_tag @competitor.image.url %> 
      <h2> Basic HQ Information </h2>
      <ul>
        <li>URL: <%= @competitor.url %> </li> 
        <li>Address: <%= @competitor.address %> </li> 
        <li>City: <%= @competitor.city %> </li>
        <li>Zip: <%= @competitor.zip %> </li> 
        <li>Country: <%= @competitor.country %> </li>  
      </ul> 

      <iframe
        width="250"
        height="250"
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBTvM3ApLcIof4tOQE-rytvJEQCPUkrzBE
          &q=<%= @competitor.full_address %>">
      </iframe>

      <h2> Company Details </h2> 
      <ul>
        <li> Number of Employees: <%= @competitor.employees %> </li>
        <li> Market Cap: <%= @competitor.market_cap %> </li>
        <li> CEO: <%= @competitor.CEO %> </li> 
        <li><%= simple_format(@competitor.key_products) %> </li> 
      </ul> 
      <h2> SWOT Analysis </h2> 
      <h3> Strengths </h3> 
      <p> <%= simple_format(@competitor.strengths) %> </p> 
      <h3> Weaknesses </h3> 
      <p> <%= simple_format(@competitor.weaknesses) %> </p>
      <h3> Opportunities </h3> 
      <p> <%= simple_format(@competitor.opportunities) %> </p> 
      <h3> Threats </h3> 
      <p> <%= simple_format(@competitor.threats) %> </p> 


      <footer> 
        <%= link_to 'Edit', edit_competitor_path(@competitor)%> | 
        <%= link_to 'Delete', @competitor, method: :delete, data: { confirm: "Are you sure?" } %> | 
        <%= link_to 'Back', competitors_path %> 
      </footer> 
  </div>
</div>