config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/rate' => 'rater#create', :as => 'rate'
  root 'static_pages#home'
  get 'static_pages/home'
  resources :ideas 
  resources :products do
    resources :features
  end
  resources :competitors
  resources :features, :only => [:show]
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/competitor.rb
class Competitor < ActiveRecord::Base

  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  def full_address
    "#{address}, #{city}, #{state} #{zip}"
  end 

end 

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  mount_uploader :image, ImageUploader

  STATUS_OPTIONS = [
    'Complete', 
    'In-Development', 
    'In-Design', 
    'On-Deck', 
    'Backlog', 
    'Unscheduled'
  ]

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_one :product
  has_many :product_ideas
  has_many :products, :through => :product_ideas
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  ratyrate_rateable 'business_impact', 'technically_feasible', 'speed_to_market'
end

app/models/kpi.rb
class Kpi < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
require 'googlecharts'
 
class Product < ActiveRecord::Base
  has_one :kpi
  has_many :features
  has_many :product_ideas
  has_many :ideas, :through => :product_ideas
  belongs_to :user
  mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :kpi

def kpi_url
  Gchart.line(:size => '400x400', :legend => ['Dollars per Month'], :axis_with_labels => ['r'], :title => kpi_name,:data => kpi_data) if !kpi_data.nil?
end

private

def kpi_data
  self.kpi.key_data.split(",").map(&:to_i) if !self.kpi.nil? && self.kpi.key_data != ''
end

def kpi_name
  'Revenue'
end

end

app/models/product_idea.rb
class ProductIdea < ActiveRecord::Base
  belongs_to :product
  belongs_to :idea
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :products
  has_many :ideas
  has_many :features 
  has_many :kpis
  has_many :competitors

  ratyrate_rater

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
   def create
     @product = Product.find(params[:product_id])
     @feature = @product.features.create(feature_params)
     redirect_to product_path(@product)
   end

  # def index
  #   @features = Feature.all 
  # end

  def show
    @feature = Feature.find(params[:id]) 
  end

  # def new
  #   @feature = Feature.new
  # end

  # def create
  #   @feature = Feature.new(feature_params) 
  #   if @feature.save 
  #     redirect_to @feature, notice: "Thanks for sharing your feature."
  #   else 
  #     render :new
  #   end 
  # end

  # def edit
  #   @feature = Feature.find(params[:id]) 
  # end

  # def update
  #   @feature = Feature.find(params[:id]) 
  #   if @feature.update_attributes(feature_params) 
  #     redirect_to @feature, notice: "Feature updated"
  #   else 
  #     render :edit 
  #   end
  # end

  # def destroy
  #   @feature = Feature.find(params[:id]) 
  #   @feature.destroy 
  #   redirect_to features_path, alert: "Feature successfully deleted." 
  # end

  # private 

  def feature_params 
     params.require(:feature).permit(:name, :description, :status, :image, :user_id)
  end 
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @ideas = Idea.all 
  end

  def show
    @idea = Idea.find(params[:id]) 
    @idea.user_id = current_user.id
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params) 
    @idea.user_id = current_user.id
    if @idea.save 
      redirect_to @idea, notice: "Thanks for sharing your idea."
    else 
      render :new
    end 
  end

  def edit
    @idea = Idea.find(params[:id]) 
  end

  def update
    @idea = Idea.find(params[:id]) 
    if @idea.update_attributes(idea_params) 
      redirect_to @idea, notice: "Idea updated"
    else 
      render :edit 
    end
  end

  def destroy
    @idea = Idea.find(params[:id]) 
    @idea.destroy 
    redirect_to ideas_path, alert: "Idea successfully deleted." 
  end

  private 

  def idea_params 
    params.require(:idea).permit(:name, :description, :image, :user_id)
  end 
  
end

app/controllers/kpis_controller.rb
class KpisController < ApplicationController 
  
  def import
  end

end 

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "prodmentum", root_path, id: "logo" %>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
        <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
      <% end %>
    </ul>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Products', products_path %></li>
      <li><%= link_to 'Ideas', ideas_path %></li>
      <li><%= link_to 'Competitors', competitors_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/navigation' %> 

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>